config/routes.rb
Rails.application.routes.draw do
  resources :request_emails
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: "top#index"
  resources :users , only: [:new , :index , :show , :update , :edit] do
    resources :followers , only: [:create , :destroy]
    resources :all_user_requests , only: [:index , :show , :create , :destroy , :new] do
      collection do
        get 'search'
        get 'user_search'
      end
    end
  end

  put '/users/:user_id/all_user_requests/:request_id/:controll_id' , to: "all_user_requests#update"

  resources :top , only: [:index , :show]
  resources :stickman_war , only: [:index , :show] do
    resources :stickman_war_detail , only: [:show]do
      resources :stickman_war_comments , only: [:create , :update , :destroy]
    end
  end
  resources :stickman_war_characters , only: [:index]
  get '/stickman_war_characters/:class_id/:character_id' , to: "stickman_war_characters#show"

  resources :requests , only: [:new , :create , :show]
  resources :movies , only: [:index , :show] do
    resources :movie_comments , only: [:create , :update , :destroy]
    collection do
      get 'search'
    end
  end
  resources :groups do
    resources :messages , only: [:create , :update , :destroy , :edit]
    resources :group_user_relations , only: [:create , :destroy]
  end
  post '/groups/:group_id/group_user_relations/:user_id/:id' , to: "group_user_relations#update"

  resources :skill_room , only: [:index]
  get "/skill_room/:type_id/:id" , to: "skill_room#show"

  resources :materials , only: [:create , :index , :new , :show]
  # それぞれの配布サイトについて詳しい情報を記載するが、
  # 自分のものについては自分のサイトであるというtype_idと、どの素材を表すかというidを使用する
  # その場合、resources内のルーティングではなく↓のルーティングが必要になる
  get "/materials/:type_id/:id" , to: "materials#show"
end

app/models/request_email.rb
class RequestEmail < ApplicationRecord
end

app/controllers/request_emails_controller.rb
class RequestEmailsController < ApplicationController
  before_action :set_request_email, only: %i[ show edit update destroy ]

  # GET /request_emails or /request_emails.json
  def index
    @request_emails = RequestEmail.all
  end

  # GET /request_emails/1 or /request_emails/1.json
  def show
  end

  # GET /request_emails/new
  def new
    @request_email = RequestEmail.new
  end

  # GET /request_emails/1/edit
  def edit
  end

  # POST /request_emails or /request_emails.json
  def create
    @request_email = RequestEmail.new(request_email_params)

    respond_to do |format|
      if @request_email.save
        format.html { redirect_to @request_email, notice: "Request email was successfully created." }
        format.json { render :show, status: :created, location: @request_email }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @request_email.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /request_emails/1 or /request_emails/1.json
  def update
    respond_to do |format|
      if @request_email.update(request_email_params)
        format.html { redirect_to @request_email, notice: "Request email was successfully updated." }
        format.json { render :show, status: :ok, location: @request_email }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @request_email.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /request_emails/1 or /request_emails/1.json
  def destroy
    @request_email.destroy
    respond_to do |format|
      format.html { redirect_to request_emails_url, notice: "Request email was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request_email
      @request_email = RequestEmail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def request_email_params
      params.require(:request_email).permit(:name, :email)
    end
end

app/helpers/request_emails_helper.rb
module RequestEmailsHelper
end

app/views/request_emails/_form.html.erb
<%= form_with(model: request_email, local: true) do |form| %>
  <% if request_email.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(request_email.errors.count, "error") %> prohibited this request_email from being saved:</h2>

      <ul>
        <% request_email.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/request_emails/edit.html.erb
<h1>Editing Request Email</h1>

<%= render 'form', request_email: @request_email %>

<%= link_to 'Show', @request_email %> |
<%= link_to 'Back', request_emails_path %>

app/views/request_emails/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Request Emails</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @request_emails.each do |request_email| %>
      <tr>
        <td><%= request_email.name %></td>
        <td><%= request_email.email %></td>
        <td><%= link_to 'Show', request_email %></td>
        <td><%= link_to 'Edit', edit_request_email_path(request_email) %></td>
        <td><%= link_to 'Destroy', request_email, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request Email', new_request_email_path %>

app/views/request_emails/new.html.erb
<h1>New Request Email</h1>

<%= render 'form', request_email: @request_email %>

<%= link_to 'Back', request_emails_path %>

app/views/request_emails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @request_email.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @request_email.email %>
</p>

<%= link_to 'Edit', edit_request_email_path(@request_email) %> |
<%= link_to 'Back', request_emails_path %>