config/routes.rb
Rails.application.routes.draw do
  resources :request_emails
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: "top#index"
  resources :users , only: [:new , :index , :show , :update , :edit] do
    resources :followers , only: [:create , :destroy]
    resources :all_user_requests , only: [:index , :show , :create , :destroy , :new] do
      collection do
        get 'search'
        get 'user_search'
      end
    end
  end

  put '/users/:user_id/all_user_requests/:request_id/:controll_id' , to: "all_user_requests#update"

  resources :top , only: [:index , :show]
  resources :stickman_war , only: [:index , :show] do
    resources :stickman_war_detail , only: [:show]do
      resources :stickman_war_comments , only: [:create , :update , :destroy]
    end
  end
  resources :stickman_war_characters , only: [:index]
  get '/stickman_war_characters/:class_id/:character_id' , to: "stickman_war_characters#show"

  resources :requests , only: [:new , :create , :show]
  resources :movies , only: [:index , :show] do
    resources :movie_comments , only: [:create , :update , :destroy]
    collection do
      get 'search'
    end
  end
  resources :groups do
    resources :messages , only: [:create , :update , :destroy , :edit]
    resources :group_user_relations , only: [:create , :destroy]
  end
  post '/groups/:group_id/group_user_relations/:user_id/:id' , to: "group_user_relations#update"

  resources :skill_room , only: [:index]
  get "/skill_room/:type_id/:id" , to: "skill_room#show"

  resources :materials , only: [:create , :index , :new , :show]
  # それぞれの配布サイトについて詳しい情報を記載するが、
  # 自分のものについては自分のサイトであるというtype_idと、どの素材を表すかというidを使用する
  # その場合、resources内のルーティングではなく↓のルーティングが必要になる
  get "/materials/:type_id/:id" , to: "materials#show"
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    # おすすめ動画は、おすすめ部分と動画一覧の両方で見えるようにする
    @search_movies = nil;
    @reccomend_movies = Movie.where(reccomend: true)
    @movies = Movie.all
    @reccomend_movies =  @reccomend_movies.sort_by{|movie|movie.id}.reverse
    @movies =  @movies.sort_by{|movie|movie.id}.reverse
  end

  def show
    @movie = Movie.find(params[:id])
    # binding.pry
    if @movie.id != params[:id].to_i
      @movie = Movie.find(Movie.all.length - params[:id].to_i)
    end
    @movie_comment = MovieComment.new
    # binding.pry
  end
  
  def search
    index
    @search_movies = Movie.search(params[:keyword])
    render :index
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/index.html.erb
<%= stylesheet_link_tag "movies/index" , :media => "all" %>
<%= render partial: "shared/header/movie_header" %>
<div class = "main_content_parent">
  <div class = "main_content">
    <p class = "section_title">動画コーナー</p>
    <div class = "only_border"></div>
    <div class = "bredcrumbs_parent">
      <% breadcrumb :movies %>
      <%= breadcrumbs separator: "&rsaquo; " %>
    </div>
    <%= form_with(url: search_movies_path, local: true, method: :get, class: "movie_search_form") do |f| %>
      <%= f.text_field :keyword , placeholder: "検索する" , class: "movie_search_input" %>
      <%= f.submit "検索" , class: "movie_search_submit" %>
    <% end %>

    <% if @search_movies != nil %>
      <p class = "small_section_title">検索結果</p>
      <div class = "all_movie_show">
        <%= render partial: "shared/movies/movie_link" , locals: {movies: @search_movies} %>
      </div>
    <% end %>

    <p class = "small_section_title">おすすめ動画</p>
    <%= render partial: "shared/movies/reccomend_movie_link" , locals: {movies: @reccomend_movies} %>

    <p class = "section_title">投稿動画一覧</p>
    <div class = "all_movie_show">
      <%= render partial: "shared/movies/movie_link" , locals: {movies: @movies} %>
    </div>
  </div>
</div>

app/views/movies/show.html.erb
<%= render partial: "shared/header/movie_header" %>
<%= stylesheet_link_tag "movies/show" , :media => "all" %>

<div class = "main_content_parent">
  <div class = "main_content">

    <div class = "bredcrumbs_parent movie_path">
      <% breadcrumb :movie_show , @movie.title , @movie.id %>
      <%= breadcrumbs separator: "&rsaquo; " %>
    </div>
  
    <%# <p class = "section_title movie_title"><%= @movie.title </p> %>
    <iframe class = "movie" src="https://www.youtube.com/embed/<%= @movie.link %>" title="YouTube video player" frameborder="0" scrolling="no" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


    <div class = "under_content">
      <p class = "small_section_title">ルンバ氏の一言</p>
      <p class = "explain"><%= "　#{@movie.explain}" %></p>
      <%= form_with  class: "comment_objects" , model: @movie_comment ,  url: movie_movie_comments_path(@movie , @movie_comment), local: true  do |f| %>
        <% unless user_signed_in? %>
          <%= f.text_area :text , readonly: true ,  disable: true , value: "ユーザー登録かサインインしないと\nコメントできません" , class: "cant_user_textarea" %>
        <% else %>
          <p style = "color:gray;" class = "hidden" id="delete_explain">新しいコメントを削除するには再読み込みをしてください</p>
          <%= f.text_area :text , id: "use_adjust" , value: @textarea_inside , class: "comment_text_area" %>
          <%= f.submit "送信" , class: "comment_submit_btn common_simple_button" , id: "submit_button" %>
        <% end %>
      <% end %>

      <div id = "all_coment_parent">
        <% @movie.movie_comments.each do |comment| %>
          <div class = "single_comment_set" id = "single_comment_set_<%= comment.id %>">
            <div style= "display:flex; justify-content:space-between">
            
            
            <%= link_to user_path(comment.user) , class:"comment_user_information" do %>
              <div class = "comment_user_icon_parent" style="display:flex; width: 50px; height:50px;">
                <% if comment.user.icon_image.attached? %>
                  <%= image_tag comment.user.icon_image , class: "comment_user_icon" %>
                <% else %>
                  <%= image_tag "defaults/user_icon_image.png" , class: "comment_user_icon" %>
                <% end %>
              </div>
              <div class = "comment_nickname_and_created_at">
                <p class = "comment_user_name"><%= comment.user.nickname %></p>
                <p class = "comment_created_at"><%= l comment.created_at %></p>
              </div>
            <% end %>
              <% if comment.user == current_user %>
                <%= link_to "削除" , movie_movie_comment_path(@movie , comment) , method: :delete , style: "margin:auto; margin-right:5px;" %>
              <% end %>

            </div>
            <p class = "comment_text hide_scroll_bar"><%= h(comment.text).gsub(/\r\n|\n|\r/, "<br>").html_safe %></p>
          </div>
        <% end %>
      </div>

      
    </div>
  </div>
</div>