config/routes.rb
Rails.application.routes.draw do
  resources :request_emails
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: "top#index"
  resources :users , only: [:new , :index , :show , :update , :edit] do
    resources :followers , only: [:create , :destroy]
    resources :all_user_requests , only: [:index , :show , :create , :destroy , :new] do
      collection do
        get 'search'
        get 'user_search'
      end
    end
  end

  put '/users/:user_id/all_user_requests/:request_id/:controll_id' , to: "all_user_requests#update"

  resources :top , only: [:index , :show]
  resources :stickman_war , only: [:index , :show] do
    resources :stickman_war_detail , only: [:show]do
      resources :stickman_war_comments , only: [:create , :update , :destroy]
    end
  end
  resources :stickman_war_characters , only: [:index]
  get '/stickman_war_characters/:class_id/:character_id' , to: "stickman_war_characters#show"

  resources :requests , only: [:new , :create , :show]
  resources :movies , only: [:index , :show] do
    resources :movie_comments , only: [:create , :update , :destroy]
    collection do
      get 'search'
    end
  end
  resources :groups do
    resources :messages , only: [:create , :update , :destroy , :edit]
    resources :group_user_relations , only: [:create , :destroy]
  end
  post '/groups/:group_id/group_user_relations/:user_id/:id' , to: "group_user_relations#update"

  resources :skill_room , only: [:index]
  get "/skill_room/:type_id/:id" , to: "skill_room#show"

  resources :materials , only: [:create , :index , :new , :show]
  # それぞれの配布サイトについて詳しい情報を記載するが、
  # 自分のものについては自分のサイトであるというtype_idと、どの素材を表すかというidを使用する
  # その場合、resources内のルーティングではなく↓のルーティングが必要になる
  get "/materials/:type_id/:id" , to: "materials#show"
end

app/models/group.rb
class Group < ApplicationRecord

  with_options presence: true do
    validates :name , length: {maximum: 100}
  end

  has_many :group_user_relations , dependent: :destroy
  has_many :users , through: :group_user_relations
  has_many :messages
  has_one_attached :image
end

app/controllers/groups_controller.rb
require 'date'
class GroupsController < ApplicationController
  before_action :check_logined
  before_action :generate_message , :generate_group , :find_user , :set_boolean
  before_action :get_group_from_params , :check_belongs_to_group , only: [:edit , :show]


  def index
  end

  def show
    @is_show = true
    @group_user_relation = GroupUserRelation.find_by(user_id: current_user.id , group_id: @group.id)
    @authority = @group_user_relation.authority_id
    @group.messages.each do |message|
      difference = Time.zone.now - message.created_at #これで何秒前に投稿されたのかがわかった
      minutes = difference / 60 
      hours = minutes / 60
      days = hours / 24  #これで何日前に投稿されたものかがわかった
      weeks = days / 7
      months = days / 30
      years = days / 365
      if minutes < 1
        message.time_type = "seconds"
        message.show_time = difference.floor
      elsif hours < 1
        message.time_type = "minutes"
        message.show_time = minutes.floor
      elsif days < 1
        message.time_type = "hours"
        message.show_time = hours.floor
      elsif weeks < 1
        message.time_type = "days"
        message.show_time = days.floor
      elsif months < 1
        message.time_type = "weeks"
        message.show_time = weeks.floor
      elsif years < 1 && months <= 2
        message.time_type = "months"
        message.show_time = months.floor
      else
        mesage.time_type = "detail_date"
        message.show_time = message.created_at
      end
    end
  end

  def new
    @group_group_user_relation = GroupGroupUserRelation.new
    
    @nil_and_users = set_all_users
    @authorities = set_authorities(5)
  end

  def create
    @group_group_user_relation = GroupGroupUserRelation.new(group_group_user_relation_params)
    if @group_group_user_relation.valid?
      @group_group_user_relation.save
      redirect_to groups_path
    else
      @authorities = set_authorities(5)
      @nil_and_users = set_all_users
      render :new
    end
  end

  def edit
    @is_edit = true
    @group_user_relation = GroupUserRelation.find_by(group_id: @group.id , user_id: current_user.id)
    @nil_and_users = set_can_add_users
    @authority = @group_user_relation.authority_id
    @send_group_user_relation = GroupUserRelation.new
    @authorities = set_authorities(@group_user_relation.authority_id)
  end

  def update
    @group = Group.find(params[:id])
    @group.update(group_params)
    redirect_to groups_path
  end

  def destroy
    @group_user_relation = GroupUserRelation.find_by(user_id: current_user.id , group_id: params[:id])
    binding.pry
    @group = Group.find(params[:id])
    if @group_user_relation.authority_id == 5
      @group.destroy
    end
    redirect_to groups_path
  end

  private 

  def group_params
    # 新規作成時はgroup_group_user_relationでsaveを行う
    params.require(:group).permit(:name , :explain , :image)
  end

  def get_group_from_params
    @group = Group.find(params[:id])
  end

  def set_can_add_users
    nil_and_users = []
    nil_user = User.new
    users = User.where.not(id: current_user.id)
    nil_and_users.push(nil_user)
    users.each do |user|
      if is_can_add_member(user)
        nil_and_users.push(user)
      end
    end
    return nil_and_users
  end

  def is_can_add_member(user)
    @group.users.each do |user_in_group|
      if user_in_group == user
        return false
      end
    end
    return true
  end

  def check_belongs_to_group
    if !is_belongs_to_group
      redirect_to groups_path
    end
  end

  def is_belongs_to_group
    @group.users.each do |user|
      if user == current_user
        return true
      end
    end
    false
  end

  def set_all_users
    nil_and_users = []
    nil_user = User.new
    users = User.where.not(id: current_user.id)
    nil_and_users.push(nil_user)
    users.each do |user|
      nil_and_users.push(user)
    end
    return nil_and_users
  end

  def set_authorities(authority_level)
    authorities = []
    (authority_level-1).times do |i|
      authorities.unshift(Authority.data.detect{|o| o[:id] == i + 1})
    end
    return  authorities
  end

  def check_logined
    if !user_signed_in?
      render "shared/prease_login"
    end 
  end

  def generate_group
    @group = Group.new
  end

  def generate_message
    @message = Message.new
  end

  def find_user
    @user = User.find(current_user.id)
  end

  def group_group_user_relation_params
    params.require(:group_group_user_relation).permit(:name , :explain , user_ids: [] , authority_ids: [])
  end

  def set_boolean 
    @is_show = false
    @is_edit = false
    @is_group = true
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_messages.html.erb
<%= stylesheet_link_tag "groups/messages" , :media => "all" %>
<script>
  function hideImageShow(obj){
    search_id = `image_show_${obj.id}`;
    show_object = document.getElementById(search_id);
    console.log(search_id);
    console.log(show_object);
    show_object.classList.add('hidden');
  };

  function showBigImage(obj){
    search_id = `image_show_${obj.id}`;
    show_object = document.getElementById(search_id);
    console.log(search_id);
    console.log(show_object);
    show_object.classList.remove('hidden');
  }

  function adjustWidthAndHeight(obj){
    showImage = document.getElementById(`image_show_image_${obj.id}`)
    showImage.removeAttribute('width');
    showImage.removeAttribute('height');

    // 戻るボタンの高さは50px
    // 戻るボタンの上の余白は10px
    // 画像プレビューエリアのwidthは親✖️0.95
    screenWidth = window.innerWidth;
    screenHeight = window.innerHeight;

    maxWidth = screenWidth * 0.95;
    maxHeight = screenHeight - (50 + 10);

    const ImageWidth = obj.offsetWidth;
    const ImageHeight = obj.offsetHeight;

    // デフォルトではwidthいっぱいに広げる、heightが飛び出るならheightいっぱいに広げる、逆にwidthから飛び出るようになるなら縦横同じにする
    let nowImageWidth = maxWidth;
    let nowImageHeight = maxWidth * (ImageHeight / ImageWidth);

    if(nowImageHeight < maxHeight){
      console.log("高さに余裕があるので横幅いっぱいに広げる");
      showImage.setAttribute('style' , `width: ${maxWidth}px;height:auto;`);
    }
    else{
      console.log("高さに余裕がありません")
      nowImageHeight = maxHeight;
      nowImageWidth = maxHeight * (ImageWidth / ImageHeight);
      if(nowImageWidth < maxWidth){
        console.log("横幅に余裕があるので縦幅いっぱいに広げる")
        showImage.setAttribute('style' , `height: ${maxHeight}px; width: auto;`);
      }
      else{
        console.log("画像が正方形なので縦横いっぱいに広げる")
        showImage.setAttribute('style' , `height: ${maxHeight}px; width: auto;`);
      }
    }
  }
</script>

<p id = "current_user_id" class = "hidden"><%= current_user.id %></p>

  <% group.messages.each do |message| %>
    <div class = "_messages_single_message hide_scroll_bar" id = "single_message_box_<%= message.id %>">
      <div class = "_messages_message_information">
        <%# 幅が600px以上だったら表示されるもの %>
        <div class = "show_more_600px">
          <a href="/users/<%= message.user.id %>" class = "_messages_user_information">
            <% if message.user.icon_image.attached? %>
              <%= image_tag message.user.icon_image.variant(resize: '500x500') , class: "_message_user_icons" %>
            <% else %>
              <%= image_tag "defaults/user_icon_image.png" , class: "_message_user_icons" %>
            <% end %>
            <p><%= message.user.nickname %></p>
            <p class = "_messages_created_at">
              <% if message.time_type == "seconds" %>
                <%= "#{message.show_time}秒前" %>
              <% elsif message.time_type == "minutes" %>
                <%= "#{message.show_time}分前" %>
              <% elsif message.time_type == "hours" %>
                <%= "#{message.show_time}時間前" %>
              <% elsif message.time_type == "days" %>
                <%= "#{message.show_time}日前" %>
              <% elsif message.time_type == "weeks" %>
                <%= "#{message.show_time}週間前" %>
              <% elsif message.time_type == "months" %>
                <%= "#{message.show_time}ヶ月前" %>
              <% elsif message.time_type == "detail_date" %>
                <%= l message.show_time %>
              <% end %>
            </p>
            <p class = "hidden"><%= l message.created_at %></p><%# JavaScriptで取得するために非表示のまま残してある %>
          </a>
        </div>

        <%# 幅が600px以下だったら表示されるもの %>
        <div class = "show_less_600px">
          <a href="/users/<%= message.user.id %>" class = "_messages_user_information">
            <% if message.user.icon_image.attached? %>
              <%= image_tag message.user.icon_image.variant(resize: '500x500') , class: "_message_user_icons" %>
            <% else %>
              <%= image_tag "defaults/user_icon_image.png" , class: "_message_user_icons" %>
            <% end %>

            <div>
              <%= message.user.nickname %>
              <p class = "_messages_created_at">
                <% if message.time_type == "seconds" %>
                  <%= "#{message.show_time}秒前" %>
                <% elsif message.time_type == "minutes" %>
                  <%= "#{message.show_time}分前" %>
                <% elsif message.time_type == "hours" %>
                  <%= "#{message.show_time}時間前" %>
                <% elsif message.time_type == "days" %>
                  <%= "#{message.show_time}日前" %>
                <% elsif message.time_type == "weeks" %>
                  <%= "#{message.show_time}週間前" %>
                <% elsif message.time_type == "months" %>
                  <%= "#{message.show_time}ヶ月前" %>
                <% elsif message.time_type == "detail_date" %>
                  <%= l message.show_time %>
                <% end %>
              </p>
              <p class = "hidden"><%= l message.created_at %></p><%# JavaScriptで取得するために非表示のまま残してある %>
            </div>
          </a>
        </div>

        <% if message.user == @user && message.text != nil %>
          <%= link_to "削除" , group_message_path(group , message) , method: :delete , class: "_messages_message_delete creater_#{message.user.id}" , remote: true , id: "destroy_button_#{message.id}" %>
        <% end %>
      </div>

      <% if message.text != nil %>
        <div id = "message_content_<%= message.id %>">
          <p class ="_message_text"><%= h(message.text).gsub(/\r\n|\n|\r/, "<br>").html_safe %></p>
          <% if message.image.attached? %>
            <div class = "_message_images_box">
            <%= image_tag message.image , class: "_message_images" , onClick: "showBigImage(this) , adjustWidthAndHeight(this)" , id: message.id %>
            <div class = "image_black"></div>
            </div>

            <div class = "image_show_background hidden" id = "image_show_<%= message.id %>">
              <div class = "image_show_center_object">
                <%= image_tag "back_button.png" , class: "image_show_back_button" , id: "#{message.id}" , onClick: "hideImageShow(this)" %>
                <%= image_tag message.image , class: "image_show_image" , id: "image_show_image_#{message.id}" %>
              </div>
            </div>
          <% end %>
        </div>
      <% else %>
        <p>メッセージは削除されました</p>
      <% end %>
    </div>
    <div class = "_messages_only_border only_border"></div>
  <% end %>

app/views/groups/_side_bar.html.erb
<%= stylesheet_link_tag "groups/side_bar" , :media => "all" %>

<div class = "_side_bar">
  <div class = "_side_bar_head top">
    <p class = "_side_bar_group_title">チャットルーム</p>

    <%# 横幅が1000pxより小さかったらヘッダー部分に自分の情報を表示する %>
    <%= link_to user_path(current_user) , class: "less_than_1000px _side_bar_top_user more_than_400px" , style:"text-decoration:none;" do %>
      <div class =  "_side_bar_image_parent">
        <% if current_user.icon_image.attached? %>
          <%= image_tag current_user.icon_image , class: "_side_bar_current_user_icon" , id: "_side_bar_current_user_icon" %>
        <% else %>
          <%= image_tag "defaults/user_icon_image.png" , class: "_side_bar_current_user_icon" , id: "_side_bar_current_user_icon" %>
        <% end %>
      </div>
      <p class = "_side_bar_current_user_name"><%= current_user.nickname %></p>
    <% end %>
  </div>

  <div class = "_side_bar_center hide_scroll_bar center">
    <div class = "_side_bar_user_information">
      <%# widthが1000pxより小さかったらグループ一覧の部分に名前を表示する %>
      <%= link_to user_path(current_user) , class: "_side_bar_current_user_link more_than_1000px more_than_1000px_user_link less_than_400px" do %>
        <div class =  "_side_bar_image_parent">
          <% if current_user.icon_image.attached? %>
            <%= image_tag current_user.icon_image , class: "_side_bar_current_user_icon" , id: "_side_bar_current_user_icon" %>
          <% else %>
            <%= image_tag "defaults/user_icon_image.png" , class: "_side_bar_current_user_icon" , id: "_side_bar_current_user_icon" %>
          <% end %>
        </div>
        <p class = "_side_bar_current_user_name"><%= current_user.nickname %></p>
      <% end %>
    </div>
    <p>所属しているルーム名</p>
    <% user.groups.each do |group| %>
      <div class = "_side_bar_single_group">
        <% if group.image.attached? %>
          <%= image_tag group.image.variant(resize: '500x500') , class: "_side_bar_group_icon" %>
        <% else %>
          <%= image_tag "defaults/group_icon.png" , class: "_side_bar_group_icon" %>
        <% end %>
        <%= link_to group.name , group_path(group) , class: "_side_bar_group_name" %>
      </div>
    <% end %>
  </div>

  <div class = "_side_bar_bottom hide_scroll_bar bottom">
    <%= link_to "ルームを作成する" , new_group_path , class: "_side_bar_create_group _side_bar_bottom_single" %>
    <%= link_to "トップページへ戻る" , "/" , class: "_side_bar_back  _side_bar_bottom_single" %>
  </div>
</div>

app/views/groups/edit.html.erb
<%= stylesheet_link_tag "groups/common" , :media => "all" %>

<div class = "parent">
  <%= render partial: "groups/side_bar" , locals: {user: @user} %>
  <%= render partial: "groups/main_bar" , locals: {is_show: @is_show , group: @group , message: @message , is_edit: @is_edit , authority: @authority} %>
</div>

<%= stylesheet_link_tag "groups/edit" , :media => "all" %>

app/views/groups/index.html.erb
<%= stylesheet_link_tag "groups/common" , :media => "all" %>

<div class = "parent">
  <%= render partial: "groups/side_bar" , locals: {user: @user} %>
  <%= render partial: "groups/main_bar" , locals: {is_show: @is_show , group: nil , message: @message , is_edit: @is_edit , authority: @authority} %>
</div>

<%= stylesheet_link_tag "groups/index" , :media => "all" %>

app/views/groups/new.html.erb
<%= stylesheet_link_tag "groups/new" , :media => "all" %>

<script>
function delete_member(element){
  delete_object = element.parentNode;
  console.log("delete_object");
  delete_object.remove();
}
</script>

<div class = "background">
    <div class = "center_object">
      <p class = "title">ルームを作成する</p>
      <%= form_with url: groups_path , method: :post , model: @group_group_user_relation , local: true do |f| %>
        <div class = "name single_box">
          <%= f.label :name , "グループ名" %><br>
          <%= f.text_field :name , class: "input_text_field" %>
        </div>

        <div class = "explain single_box">
          <%= f.label :explain , "グループの説明" %><br>
          <%= f.text_area :explain , class: "input_text_field" %>
        </div>

        <%= f.label :user , "追加するユーザー" %><br>
          <input type="hidden" name= "group_group_user_relation[user_ids][]" value= <%= current_user.id %> >
          <input type="hidden" name= "group_group_user_relation[authority_ids][]" value = "5" >

        <div class = "members_box single_box" id = "root_member_box">
          <div class = "member_information_box">
          
            <select class="user_select" name="group_group_user_relation[user_ids][]">
              <% @nil_and_users.each do |user| %>
                <% if user.id != nil %>
                  <option value = <%= user.id %> ><%= user.nickname.slice(0,9) %></option>
                <% else %>
                  <option value = nil ><%= "ユーザーを選択してください" %></option>

                <% end %>
              <% end %>
            </select>
          
            <div class = "authority_box">
              <%= f.label :authority_id , "権限：" %>
              <select class="authority_select" name="group_group_user_relation[authority_ids][]">
                <% @authorities.each do |authority| %>
                  <option value = <%= authority[:id] %>><%= authority[:name] %></option>
                <% end %>
              </select>
              <%# 上のselectは、↓ を参考に作った ↓のもののコメントアウトを外すことはまずない %>
              <%# <%= f.collection_select(:authority_id , Authority.all , :id , :name , {} , {class: "authority_select"} ) %>
            </div>

          </div>

          <p class = "common_simple_button add_member_button delete_member_button" id = "delete_button0" onClick="delete_member(this)">このメンバーを除外する</p>
        </div>

        <p class = "add_member_button common_simple_button" id = "add_member">メンバーを増やす</p><br>

        <%= f.submit "作成する" , class: "common_simple_button create_button" , id: "add_member" %>
      <% end %>
  </div>
</div>

app/views/groups/show.html.erb
<%= stylesheet_link_tag "groups/common" , :media => "all" %>

<%= image_tag "back_button.png" , class: "hidden" , id: "for_get_back_button" %>

<div class = "parent">
  <%= render partial: "groups/side_bar" , locals: {user: @user} %>
  <%= render partial: "groups/main_bar" , locals: {is_show: @is_show , group: @group , message: @message , is_edit: @is_edit , authority: @authority} %>
</div>

<%= stylesheet_link_tag "groups/show" , :media => "all" %>