config/routes.rb
Rails.application.routes.draw do
  resources :request_emails
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: "top#index"
  resources :users , only: [:new , :index , :show , :update , :edit] do
    resources :followers , only: [:create , :destroy]
    resources :all_user_requests , only: [:index , :show , :create , :destroy , :new] do
      collection do
        get 'search'
        get 'user_search'
      end
    end
  end

  put '/users/:user_id/all_user_requests/:request_id/:controll_id' , to: "all_user_requests#update"

  resources :top , only: [:index , :show]
  resources :stickman_war , only: [:index , :show] do
    resources :stickman_war_detail , only: [:show]do
      resources :stickman_war_comments , only: [:create , :update , :destroy]
    end
  end
  resources :stickman_war_characters , only: [:index]
  get '/stickman_war_characters/:class_id/:character_id' , to: "stickman_war_characters#show"

  resources :requests , only: [:new , :create , :show]
  resources :movies , only: [:index , :show] do
    resources :movie_comments , only: [:create , :update , :destroy]
    collection do
      get 'search'
    end
  end
  resources :groups do
    resources :messages , only: [:create , :update , :destroy , :edit]
    resources :group_user_relations , only: [:create , :destroy]
  end
  post '/groups/:group_id/group_user_relations/:user_id/:id' , to: "group_user_relations#update"

  resources :skill_room , only: [:index]
  get "/skill_room/:type_id/:id" , to: "skill_room#show"

  resources :materials , only: [:create , :index , :new , :show]
  # それぞれの配布サイトについて詳しい情報を記載するが、
  # 自分のものについては自分のサイトであるというtype_idと、どの素材を表すかというidを使用する
  # その場合、resources内のルーティングではなく↓のルーティングが必要になる
  get "/materials/:type_id/:id" , to: "materials#show"
end

app/models/all_user_request.rb
class AllUserRequest < ApplicationRecord
  attr_accessor :time_difference
  with_options presence: true do 
    validates :text
    validates :is_open_name
    validates :user
    validates :request_creater_id
    validates :status , numericality: {only_integer: true}
  end

  belongs_to :user
  belongs_to :request_creater , class_name: "User"
end

app/controllers/all_user_requests_controller.rb
require "date"
class AllUserRequestsController < ApplicationController
  before_action :check_login
  before_action :check_same_user , only: [:show , :update , :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.find(params[:user_id])
    @all_user_request = AllUserRequest.new
  end

  def create
    @all_user_request = AllUserRequest.new(all_user_request_params)
    @all_user_request.status = 0
    if @all_user_request.valid?
      @user = User.find(params[:user_id])
      if check_no_same_request(@user , @all_user_request)
        @all_user_request.save
      end
    else
      @user = User.find(params[:user_id])
      render :new
    end
  end

  def show
    @user = User.find(params[:user_id])
    # @request = AllUserRequest.find_by(id: params[:id] , user_id: params[:user_id])
    # binding.pry
    if params[:id] == "status_up"
      @requests = @user.all_user_requests.order("status DESC")
      @sort_type = "進んでいる順"

    elsif params[:id] == "status_down"
      @requests = @user.all_user_requests.order("status ASC")
      @sort_type = "進んでいない順"

    elsif params[:id] == "created_at_up"
      @requests = @user.all_user_requests.order("created_at DESC")
      @sort_type = "新しい順"

    elsif params[:id] == "created_at_down"
      @requests = @user.all_user_requests.order("created_at ASC")
      @sort_type = "古い順"

    else
      @requests = @user.all_user_requests
    end

    @requests.each do |request|
      # time_difference
      difference = Time.zone.now - request.created_at #この値が「秒」となる
      minutes = difference / 60 
      hours = minutes / 60
      days = hours / 24  #これで何日前に投稿されたものかがわかった
      weeks = days / 7
      months = days / 30
      years = days / 365
      if minutes < 1
        request.time_difference = difference.floor.to_s+"秒前"
      elsif hours < 1
        request.time_difference = minutes.floor.to_s+"分前"
      elsif days < 1
        request.time_difference = hours.floor.to_s+"時間前"
      elsif weeks < 1
        request.time_difference = days.floor.to_s+"日前"
      elsif months < 1
        request.time_difference = weeks.floor.to_s+"週間前"
      elsif years < 1 && months <= 2
        request.time_difference = months.floor.to_s+"ヶ月前"
      else
        request.time_difference = nil
      end
    end

    @request
  end

  def destroy
    @all_user_request = AllUserRequest.find_by(id: params[:id] , user_id: params[:user_id])
    @all_user_request.destroy
    # render :show
    ActionCable.server.broadcast 'all_user_request_channel' , request: @all_user_request , control_type: "destroy"
  end

  def update
    @all_user_request = AllUserRequest.find_by(id: params[:request_id] , user_id: params[:user_id])
    if params[:controll_id] == "finished"
      @all_user_request.status = 2
    elsif params[:controll_id] == "received"
      @all_user_request.status = 1
    elsif params[:controll_id] == "untreated"
      @all_user_request.status = 0
    end
    @all_user_request.save
    ActionCable.server.broadcast 'all_user_request_channel' , request: @all_user_request , control_type: "update"
  end

  def search
    if params[:keyword] != ""
      return_request = AllUserRequest.where("text LIKE?" , "%#{params[:keyword]}%").where(user_id: params[:user_id])
      @searched_requests = return_request
      # binding.pry
    end
    show
    render :show
  end

  def user_search
    if params[:keyword] != ""
      return_users = User.where("nickname LIKE?", "%#{params[:keyword]}%")
      return_users_by_account_name = User.where("account_name LIKE?" , "%#{params[:keyword]}%")
      @searched_users = []
      return_users.each do |user|
        @searched_users << user
      end

      # 統一せ雨を持たせるためにここでも既に追加されていないことを確認する
      return_users.each do |user|
        if !check_added_user(user , @searched_users)
          @searched_users << user
        end
      end

      # ユーザー名の部分で既に追加されていないことを確認してから配列に追加する
      return_users_by_account_name.each do |user|
        if !check_added_user(user , @searched_users)
          @searched_users << user
        end
      end
    end
    index
    render :index
  end

  private 

  def all_user_request_params
    params.require(:all_user_request).permit(:text , :is_open_name).merge(request_creater_id: current_user.id , user_id: params[:user_id])
  end

  def check_login
    if !user_signed_in?
      redirect_to new_request_path
    end
  end

  def check_same_user
    if params[:user_id].to_i != current_user.id
      redirect_to user_all_user_requests_path("index")
    end
  end

  def check_added_user(add , all)
    all.each do |added|
      if added == add
        return true
      end
    end
    return false
  end

  def check_no_same_request(users , create_request)
    users.all_user_requests.each do |request|
      if create_request.text == request.text
        if create_request.request_creater_id == request.request_creater_id
          return false
        end
      end
    end
    return true
  end
end

app/helpers/all_user_requests_helper.rb
module AllUserRequestsHelper
end

app/views/all_user_requests/_request.html.erb
<%# ここの内容はshow.scssから調整されている %>
        <%  if request.status == 0 
              status = nil
              color_class = "untreated_color"
            elsif request.status == 1
              status = "received"
              color_class = "received_color"
            elsif request.status == 2
              status = "finished"
              color_class = "finished_color"
            end
        %>
        <div class = "single_request_parent">

        <div class = "single_request <%= color_class %> request_class_<%= request.id %>">
          <div class="single_user">
            <div class = "user_icon_parent">
              <% if request.request_creater.icon_image.attached? %>
                <%= image_tag request.request_creater.icon_image , class: "user_icon_image" %>
              <% else %>
                <%= image_tag "defaults/user_icon_image.png" , class: "user_icon_image" %>
              <% end %>
            </div>
            <p class="user_nickname"><%= request.request_creater.nickname %></p>
          </div>

        <%# request_contentとopen_all_text_buttonの順番を変えるとopen_sort内の処理に影響が出る、順番は極力変えない %>
        <p class="request_content"><%= h(request.text).gsub(/\r\n|\n|\r/, "<br>").html_safe %></p>
        <p class = "common_simple_button open_all_text_button">全文を見る</p>

          <% if request.user == current_user %>
            <div class = "control_buttons">
              <%= link_to "/users/#{request.user.id}/all_user_requests/#{request.id}/finished" , method: :put , class: "control_button_link" do %>
                <i class="fas fa-award control_button_awesome"></i>完了
              <% end %>

              <%= link_to "/users/#{request.user.id}/all_user_requests/#{request.id}/received" , method: :put , class: "control_button_link" do %>
                <i class="fas fa-check control_button_awesome"></i>採用する
              <% end %>

              <%= link_to "/users/#{request.user.id}/all_user_requests/#{request.id}/untreated" , method: :put , class: "control_button_link" do %>
                <i class="fas fa-arrow-alt-circle-left control_button_awesome"></i>元に戻す
              <% end %>

              <%= link_to user_all_user_request_path(request.user , request) , method: :delete , class: "control_button_link" do %>
                <i class="fas fa-times control_button_awesome"></i>この世から消し去る
              <% end %>
            </div>
          <% end %>

          <p class = "now_status now_status_<%= request.id %>">現在の状況
          <span class = "now_status_detail">
            <%  if status == nil %>
              未処理
            <% elsif status == "finished" %>
              <i class="fas fa-award status_awesome"></i></i>完了！
            <%elsif status == "received" %>
              <i class="fas fa-check status_awesome"></i>採用！
            <% end %>
          </span>
            <% if request.time_difference != nil %>
              <p style = "display:inline-block;padding-right:10px;min-width:150px;">作成：<%= request.time_difference %></p>
            <% else %>
              <p style = "display:inline-block;padding-right:10px;">作成日時：<%= l request.created_at %></p>
            <% end %>
            <p style = "display:inline-block;">リクエストID：<%= request.id %></p>
          </p>
      </div>
        </div>

app/views/all_user_requests/_single_user.html.erb
<%# common.scssから調整されている %>
<%= link_to new_user_all_user_request_path(user) , class: "single_user_parent" do %>
  <div class = "single_user">
    <div class = "user_icon_image_parent">
      <% if user.icon_image.attached? %>
        <%= image_tag user.icon_image , class: "user_icon_image" %>
      <% else %>
        <%= image_tag "defaults/user_icon_image.png" , class: "user_icon_image" %>
      <% end %>
    </div>
    <p><%= user.nickname %></p>
  </div>
<% end %>

app/views/all_user_requests/create.html.erb
<%= render partial: "shared/header/root_header" , locals: {title: "リクエストボックス"} %>
<%= stylesheet_link_tag "all_user_requests/common" , media: "all" %>
<%= stylesheet_link_tag "all_user_requests/create" , media: "all" %>

<div class = "main_content_parent">
  <div class = "main_content">
    <p class = "section_title">送信が完了しました</p>
    <%= link_to "まだまだ送る" , new_user_all_user_request_path(params[:user_id]) , class:"resend_link link" %>
    <%= link_to "ユーザー一覧に戻る" , user_all_user_requests_path("index") , class: "back_link link" %>
  </div>
</div>

app/views/all_user_requests/index.html.erb
<%= render partial: "shared/header/root_header" , locals: {title: "リクエストボックス"} %>
<%= stylesheet_link_tag "all_user_requests/common" , media: "all" %>
<%= stylesheet_link_tag "all_user_requests/index" , media: "all" %>

<div class = "main_content_parent">
  <div class = "main_content">
    <p class = "section_title">ユーザー一覧</p>
    <%= link_to "マイページへ" , user_all_user_request_path(current_user , "all") , class: "my_page_link" %>

    <%= form_with url: user_search_user_all_user_requests_path("user_search") , local: true , method: :get , class: "search_form" do |f| %>
      <%= f.text_field :keyword , placeholder: "アカウント名、ニックネームで検索する" , class: "search_input" %>
      <%= f.submit "検索" , class: "search_submit" %>
    <% end %>

    <div class = "user_parent">
      <% if @searched_users != nil %>
        <% if @searched_users.length != 0 %>
          <p class = "small_section_title">検索結果</p>
        <% end %>
        <% @searched_users.each do |user| %>
          <% if current_user != user %>
            <%= render partial: "single_user" , locals: {user: user} %>
          <% end %>
        <% end %>
        <% if @searched_users.length != 0 %>
          <p class = "small_section_title">ユーザー一覧</p>
        <% end %>
      <% end %>

      <% @users.each do |user| %>
        <% if user != current_user %>
          <%= render partial: "single_user" , locals: {user: user} %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/all_user_requests/new.html.erb
<%= render partial: "shared/header/root_header" , locals: {title: "リクエストボックス"} %>
<%= stylesheet_link_tag "all_user_requests/common" , media: "all" %>
<%= stylesheet_link_tag "all_user_requests/new" , media: "all" %>
<div class = "main_content_parent">
  <div class = "main_content">
    <p class = "section_title">リクエスト作成ページ</p>

    <div class = "user_parent">
      <div class= "single_user_parent">
        <div class = "single_user">
          <div class = "user_icon_image_parent">
            <% if @user.icon_image.attached? %>
              <%= image_tag @user.icon_image , class: "user_icon_image" %>
            <% else %>
              <%= image_tag "defaults/user_icon_image.png" , class: "user_icon_image" %>
            <% end %>
          </div>
          <p><%= @user.nickname %></p>
        </div>
      </div>
    </div>

    <%= form_with  class: "all_user_requests_objects" , model: @all_user_request ,  url: user_all_user_requests_path(@user), local: true  do |f| %>
      <p class = "request_explain">リクエストの内容を入力しよう！</p>
      <%= f.text_area :text , id: "use_adjust" , value: @textarea_inside , class: "all_user_requests_text_area" %>
      <div style = "width:100%;display:flex;justify-content:center;">
        <label class = "request_checkbox_parent">
          <input type="checkbox" value="<%= @user.nickname %>から名前が見えるようにする" class="request_checkbox"><%= @user.nickname %>から名前が見えるようにする
        </label>
      </div>
      <%= f.text_field :is_open_name , value: "true" , style: "display:none;" %>
      <%= f.submit "送信" , class: "all_user_requests_submit_btn common_simple_button" , id: "submit_button" %>
    <% end %>
  </div>
</div>

app/views/all_user_requests/show.html.erb
<%= render partial: "shared/header/root_header" , locals: {title: "リクエストボックス"} %>
<%= stylesheet_link_tag "all_user_requests/common" , media: "all" %>
<%= stylesheet_link_tag "all_user_requests/show" , media: "all" %>

<div class = "main_content_parent">
  <div class = "main_content">
    <p class = "section_title"><%= @user.nickname %>のマイページ</p>
    <% if @user.all_user_requests.length != 0 %>
      <%= form_with url:search_user_all_user_requests_path(params[:user_id]) , local: true , method: :get , class: "search_form" do |f| %>
        <%= f.text_field :keyword , placeholder: "リクエストを検索するにはこれを使用してください" , class: "search_input" %>
        <%= f.submit "検索" , class: "search_submit" %>
      <% end %>


      <div class = "sort_buttons" style="display:none;">
        <p class = "sort_title">並び替え</p>
        <div>
          <div class = "status_sort_buttons">
            <p class = "sort_small_title">進行状況別</p>
            <%= link_to "進んでいる順" , user_all_user_request_path(params[:user_id] , "status_up") , class: "common_simple_button status_up_to_down" %><br>
            <%= link_to "進んでいない順" , user_all_user_request_path(params[:user_id] , "status_down") , class: "common_simple_button status_down_to_up" %>
          </div>
          
          <div class = "created_at_sort_buttons">
            <p class = "sort_small_title">作成日時順</p>
            <%= link_to "新しい順" , user_all_user_request_path(params[:user_id] , "created_at_up") , class: "common_simple_button created_at_up_to_down" %><br>
            <%= link_to "古い順" , user_all_user_request_path(params[:user_id] , "created_at_down") , class: "common_simple_button created_at_down_to_up" %>
          </div>
        </div>
      </div>
      <p class = "open_sort_button_border"></p>
      <p class = "common_simple_button open_sort_button">並び替えを使用する</p>

      <% if @searched_requests != nil %>
        <% if @searched_requests.length >= 1 %>
          <p class = "small_section_title">検索結果</p>
          <%= render partial: "request" , collection: @searched_requests %>
          <p class = "small_section_title second_small_section_title">全てのリクエスト</p>
        <% end %>
      <% elsif @sort_type != nil %>
        <p class = "small_section_title"><%= @sort_type %></p>
      <% end %>
      <%= render partial: "request" , collection: @requests %>
    <% else %>
      <p class = "no_requests">まだリクエストは<br class = "br_less_than_400px">届いていません！</p>
      <%= link_to "更新する" , user_all_user_request_path(params[:user_id] , "all") , class: "reload_button common_simple_button" %>
    <% end %>
  </div>
</div>